# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- develop

pool:
  vmImage: 'windows-latest'

name: $(Major).$(Minor)$(Rev:.r)-beta

variables:
- group: 'versioning'
- name: 'buildConfiguration'
  value: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetAuthenticate@0
  inputs:
    forceReinstallCredentialProvider: true
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'byBuildNumber'

- script: |
    'dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --api-key oy2kw5sqefrt3tcqp7da4tzyrn245qcupe4mzq4ruf7mx4 --source https://api.nuget.org/v3/index.json'


