# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- develop

pool:
  vmImage: 'windows-latest'

name: $(Major).$(Minor)$(Rev:.r)-beta

variables:
- group: versioning
- group: nuget
- name: 'buildConfiguration'
  value: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetAuthenticate@0
  inputs:
    forceReinstallCredentialProvider: true
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    configuration: '$(buildConfiguration)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'Build.BuildNumber'

- script:  dotnet nuget push $(Build.ArtifactStagingDirectory)\*.nupkg --api-key $(apiKey) --source https://api.nuget.org/v3/index.json

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'custom'
#     custom: 'nuget push'
#     arguments: '$(Build.ArtifactStagingDirectory)/*.nupkg --api-key $(apiKey) --source https://api.nuget.org/v3/index.json'
